name: qr_code_scanner
description: QR code scanner that can be embedded inside flutter. It uses zxing in Android and MTBBarcode scanner in iOS.
version: 0.0.12
author: Julius Canute <juliuscanute at touchcapture.net>
homepage: https://juliuscanute.com
repository: https://github.com/juliuscanute/qr_code_scanner

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^1.0.10+1
  font_awesome_flutter: ^8.5.0
  provider: ^3.1.0
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1
  image: ^2.1.4
  color: ^2.1.1
flutter:
  plugin:
    androidPackage: net.touchcapture.qr.flutterqr
    pluginClass: FlutterQrPlugin
